language: php

php:
- 7
- 5.6
- 5.5

env:
- PHPUNIT_VERSION=4.7.*
- PHPUNIT_VERSION=4.8.*
- PHPUNIT_VERSION=5.0.*
- PHPUNIT_VERSION=5.1.*
- PHPUNIT_VERSION=5.2.*
- PHPUNIT_VERSION=5.3.*
- PHPUNIT_VERSION=5.4.*
- PHPUNIT_VERSION=*
- PHPUNIT_VERSION=fork

matrix:
  allow_failures:
    - env: PHPUNIT_VERSION=4.7.*
    - env: PHPUNIT_VERSION=4.8.*
    - env: PHPUNIT_VERSION=5.0.*
    - env: PHPUNIT_VERSION=5.1.*
    - env: PHPUNIT_VERSION=5.2.*
    - env: PHPUNIT_VERSION=5.3.*
    - env: PHPUNIT_VERSION=5.4.*
    - php: 5.5
      env: PHPUNIT_VERSION=fork

sudo: false

install:
 - if [[ "$PHPUNIT_VERSION" == "fork" ]]; then composer config repositories.glady/phpunit vcs https://github.com/glady/phpunit && travis_retry composer require glady/phpunit:dev-master; else travis_retry composer require phpunit/phpunit:$PHPUNIT_VERSION; fi
 - travis_retry composer install --no-interaction --prefer-source

script:
 - vendor/bin/phpunit --testsuite Issue2136ByTestSuite --debug # not executing BTest
 - vendor/bin/phpunit --testsuite Issue2136Test # failing when bug is not solved

